### ISSUE TITLE
panic when getting work

### ISSUE THREAD

**Issue by magnusmanske** [mattsse/crossref-rs#1]
So great to find this crate! Rust grows on me daily :-)

I am trying some very simple test code, using your example paper:
```
    let client = Crossref::builder().build().unwrap();
    let work = client.work("10.1037/0003-066X.59.1.29").unwrap();
    dbg!(work);
```
But I get a panic (backtrace):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { ctx: stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::he135e868fd74a8c9 (0x10e909505)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h631e316463fa96ab (0x10e90a1ce)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: <failure::context::Context<D>>::new::h267f1c55171969ba (0x10e340991)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:84
   3: <crossref::error::Error as core::convert::From<crossref::error::ErrorKind>>::from::hb7f3ce0c6afe4e5a (0x10e32bfbc)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/crossref-0.1.0/src/error.rs:77
   4: <T as core::convert::Into<U>>::into::h07cc81735444d9cc (0x10e32a60c)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/convert.rs:441
   5: <crossref::error::Error as core::convert::From<serde_json::error::Error>>::from::h5ce4f05b21aa4fe9 (0x10e32c09c)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/crossref-0.1.0/src/error.rs:89
   6: crossref::Crossref::get_response::hb6eef7e1b26e8a72 (0x10e336516)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/crossref-0.1.0/src/lib.rs:288
   7: crossref::Crossref::work::h45e70744a81dc196 (0x10e3369a2)
             at /Users/mm6/.cargo/registry/src/github.com-1ecc6299db9ec823/crossref-0.1.0/src/lib.rs:356
   8: main::main::hb5c6dd26f5ebe32c (0x10e282442)
             at src/bin/main.rs:15
   9: std::rt::lang_start::{{closure}}::hc2db45f29c6f06e4 (0x10e27f9a1)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  10: std::panicking::try::do_call::hbdc2ad4ee791d633 (0x10e95ff27)
             at src/libstd/panicking.rs:297
  11: ___rust_maybe_catch_panic (0x10e96373e)
             at src/libpanic_unwind/lib.rs:92
  12: std::rt::lang_start_internal::h3dc68cf5532522d7 (0x10e960a1c)
             at src/libstd/rt.rs:48
  13: std::rt::lang_start::hcad8a588769f53fd (0x10e27f981)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  14: _main (0x10e282721)

invalid serde: invalid type: floating point `1`, expected i32 }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
  10: main::main
             at src/bin/main.rs:15
  11: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:92
  14: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  16: main::main
````

**Comment by mattsse** [comment]
Great to hear!

Thanks for the issue. I already found the problem.
the crossref api docs doesn't differentiate between floats and ints. Unfortunately i declared the work's score as an `i32` https://github.com/MattsSe/crossref-rs/blob/master/src/response/work.rs#L95  but the score is returned as float: https://api.crossref.org/works/10.1037/0003-066X.59.1.29


I'll fix this tonight.

**Comment by magnusmanske** [comment]
So cool to get a quick, positive reply :-)

Thank you!!!
